# Generated by Django 5.2.5 on 2025-09-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_category', models.CharField(max_length=10)),
                ('q_title', models.CharField(default='question title', max_length=200)),
                ('question', models.TextField()),
                ('q_testcase', models.TextField()),
                ('q_answer', models.TextField()),
            ],
        ),
    ]
